In [1]:
import numpy as np
import pandas as pd
from scipy.io import loadmat

In [2]:
def load_weight(path):
    data = loadmat(path)
    return data['Theta1'], data['Theta2']

In [3]:
theta1, theta2 = load_weight('datasets/ex3weights.mat')
theta1, theta2

(array([[-2.25623899e-02, -1.05624163e-08,  2.19414684e-09, ...,
         -1.30529929e-05, -5.04175101e-06,  2.80464449e-09],
        [-9.83811294e-02,  7.66168682e-09, -9.75873689e-09, ...,
         -5.60134007e-05,  2.00940969e-07,  3.54422854e-09],
        [ 1.16156052e-01, -8.77654466e-09,  8.16037764e-09, ...,
         -1.20951657e-04, -2.33669661e-06, -7.50668099e-09],
        ...,
        [-1.83220638e-01, -8.89272060e-09, -9.81968100e-09, ...,
          2.35311186e-05, -3.25484493e-06,  9.02499060e-09],
        [-7.02096331e-01,  3.05178374e-10,  2.56061008e-09, ...,
         -8.61759744e-04,  9.43449909e-05,  3.83761998e-09],
        [-3.50933229e-01,  8.85876862e-09, -6.57515140e-10, ...,
         -1.80365926e-06, -8.14464807e-06,  8.79454531e-09]]),
 array([[-0.76100352, -1.21244498, -0.10187131, -2.36850085, -1.05778129,
         -2.20823629,  0.56383834,  1.21105294,  2.21030997,  0.44456156,
         -1.18244872,  1.04289112, -1.60558756,  1.30419943,  1.37175046,
       

In [4]:
def load_data(path):
    data = loadmat(path)
    return data['X'], data['y']

In [5]:
X, y = load_data('datasets/ex3data1.mat')
X, y

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]), array([[10],
        [10],
        [10],
        ...,
        [ 9],
        [ 9],
        [ 9]], dtype=uint8))

In [6]:
def sigmoid_function(z):
    return 1 / (1 + np.exp(-z))

In [7]:
X = np.insert(X, 0, values=np.ones(X.shape[0]), axis=1)
y = y.flatten()

In [8]:
a1 = X
z2 = a1 @ theta1.T

In [12]:
z2 = np.insert(z2, 0, 1, axis=1)
a2 = sigmoid_function(z2)

In [13]:
z3 = a2 @ theta2.T

In [14]:
a3 = sigmoid_function(z3)

In [15]:
y_pred = np.argmax(a3, axis=1) + 1
acc = np.mean(y_pred == y)
print('acc is {}'.format(acc))

acc is 0.9752
